-- ==============================================
-- SCRIPT DE BASE DE DATOS - SISTEMA CLÍNICA
-- ==============================================

CREATE DATABASE IF NOT EXISTS clinica;
USE clinica;

-- Tabla ASISTENTE
CREATE TABLE ASISTENTE (
    ID_ASISTENTE INT PRIMARY KEY,
    NOMBRE VARCHAR(45),
    TURNO VARCHAR(45)
);

-- Tabla TIPO_DE_CONSULTA
CREATE TABLE TIPO_DE_CONSULTA (
    ID_CONSULTA INT PRIMARY KEY,
    DISPONIBILIDAD TINYINT
);

-- Tabla PACIENTE
CREATE TABLE PACIENTE (
    ID_PACIENTE INT PRIMARY KEY,
    NOMBRE VARCHAR(45),
    EDAD INT
);

-- Tabla CONSULTORIO
CREATE TABLE CONSULTORIO (
    ID_CONSULTORIO INT PRIMARY KEY
);

-- Tabla MEDICO
CREATE TABLE MEDICO (
    ID_MEDICO INT PRIMARY KEY,
    NOMBRE VARCHAR(45),
    TELEFONO VARCHAR(45),
    GENERO VARCHAR(45),
    ESPECIALIDAD VARCHAR(45)
);

-- Tabla ENFERMERA
CREATE TABLE ENFERMERA (
    ID_ENFERMERA INT PRIMARY KEY,
    NOMBRE VARCHAR(45),
    TURNO VARCHAR(45)
);

-- Tabla ENFERMERA_MEDICO (relación N:M)
CREATE TABLE ENFERMERA_MEDICO (
    ID_ENFERMERA INT,
    ID_MEDICO INT,
    PRIMARY KEY (ID_ENFERMERA, ID_MEDICO),
    FOREIGN KEY (ID_ENFERMERA) REFERENCES ENFERMERA(ID_ENFERMERA),
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID_MEDICO)
);

-- Tabla CITA
CREATE TABLE CITA (
    ID_CITA INT PRIMARY KEY,
    ID_MEDICO INT,
    ID_PACIENTE INT,
    ID_CONSULTORIO INT,
    FECHA DATE,
    HORA TIME,
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID_MEDICO),
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE),
    FOREIGN KEY (ID_CONSULTORIO) REFERENCES CONSULTORIO(ID_CONSULTORIO)
);

-- Tabla HISTORIA_CLINICA
CREATE TABLE HISTORIA_CLINICA (
    ID_HISTORIA_CLINICA INT PRIMARY KEY,
    ID_CITA INT,
    FECHA DATE,
    HORA TIME,
    ESTADO VARCHAR(45),
    FOREIGN KEY (ID_CITA) REFERENCES CITA(ID_CITA)
);

-- Tabla USUARIOS (Autenticación)
CREATE TABLE USUARIOS (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(45) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROL VARCHAR(45) NOT NULL
);

-- Usuario Administrador por Defecto
INSERT IGNORE INTO USUARIOS (USERNAME, PASSWORD, ROL) VALUES ('admin', 'admin123', 'Administrador');
